### ISSUE TITLE
sge zombie compute nodes

### ISSUE THREAD

**Issue by karlvirgil** [aws/aws-parallelcluster#298]
I have a cfncluster instance using sge as the scheduler.  I have a 10 node job and a one node job running.  I had one other job stall, and the compute node (**ip-10-15-20-7**) appears to be offline (doens't show up in the aws console).  However, the compute node still keeps showing up in the sge qhost

```
$)qhost
HOSTNAME                ARCH         NCPU NSOC NCOR NTHR  LOAD  MEMTOT  MEMUSE  SWAPTO  SWAPUS
----------------------------------------------------------------------------------------------
global                  -               -    -    -    -     -       -       -       -       -
ip-10-15-20-136         lx-amd64       72    2   36   72 36.05  137.3G   10.0G     0.0     0.0
ip-10-15-20-170         lx-amd64       72    2   36   72 60.08  137.3G    2.4G     0.0     0.0
ip-10-15-20-174         lx-amd64       72    2   36   72 35.95  137.3G   10.1G     0.0     0.0
ip-10-15-20-178         lx-amd64       72    2   36   72 36.02  137.3G   10.2G     0.0     0.0
ip-10-15-20-179         lx-amd64       72    2   36   72 35.96  137.3G    9.9G     0.0     0.0
ip-10-15-20-205         lx-amd64       72    2   36   72 35.89  137.3G    9.8G     0.0     0.0
ip-10-15-20-208         lx-amd64       72    2   36   72 36.00  137.3G   10.4G     0.0     0.0
ip-10-15-20-236         lx-amd64       72    2   36   72 35.93  137.3G    9.9G     0.0     0.0
ip-10-15-20-254         lx-amd64       72    2   36   72 35.92  137.3G    9.9G     0.0     0.0
ip-10-15-20-37          lx-amd64       72    2   36   72 35.89  137.3G    9.9G     0.0     0.0
ip-10-15-20-7           lx-amd64       72    2   36   72     -  137.3G       -     0.0       -
ip-10-15-20-74          lx-amd64       72    2   36   72 35.96  137.3G    9.8G     0.0     0.0

$)qstat
job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID
-----------------------------------------------------------------------------------------------------------------
     27 0.60500 plume      centos       r     01/16/2018 14:58:28 all.q@ip-10-15-20-37.ec2.inter   720
     41 0.50500 n050       centos       r     01/17/2018 10:37:13 all.q@ip-10-15-20-170.ec2.inte    72
```

as is shown by this line:
`ip-10-15-20-7           lx-amd64       72    2   36   72     -  137.3G       -     0.0       -
`

Two questions:  1) why does this occur that even though the compute node appears to have died, sge still keeps it in qhost, and 2) is there a way to manually clean this up so that only actively running nodes show up?

**Comment by karlvirgil** [comment]
I don't know the reason the host died.  It no longer shows up in the EC2 terminal.  
This state showed up almost immediately after the job died.  It didn't self resolve.  In fact, the queue still shows this compute node, albeit in a zombie state.

**Comment by jocherry** [comment]
OK this sounds like a known issue with SGE:
https://github.com/awslabs/cfncluster-node/issues/10
and this link has some suggestions on how to resolve: 
https://forums.aws.amazon.com/thread.jspa?messageID=747497&#747497

Hopefully this is helpful.

**Comment by enrico-usai** [comment]
This bug has been resolved in the upcoming 1.6.0 release:
https://github.com/awslabs/cfncluster/blob/develop/CHANGELOG.rst#160

If you are willing to test the release candindate you can install it with: 
`pip install -Iv cfncluster==1.6.0rc1`

Please keep us updated if you have the opportunity to test the rc1 or please stay tuned for the upcoming 1.6.0 release.

**Comment by pro100frol** [comment]
Unfortunately it wasn't fixed. I can confirm that the bug is still there.

**Comment by enrico-usai** [comment]
Ok thank you for reporting this. We'll keep you updated on this.

**Comment by pro100frol** [comment]
> Ok thank you for reporting this. We'll keep you updated on this.

thank you guys!

**Comment by lukeseawalker** [comment]
Hi all,
this issue has been fixed by: [aws/aws-parallelcluster-node#98](https://github.com/aws/aws-parallelcluster-node/pull/98)
When all the jobs referencing the terminated instance will be delete, then the host will be removed from the scheduler. We have also plans to change the default SGE configuration in order to allow non-admin users to be able to force delete jobs [aws/aws-parallelcluster-cookbook#259](https://github.com/aws/aws-parallelcluster-cookbook/pull/259)

I'm going to close this case since the patch has been merged in the develop branch.
It will be available in the next version of AWS ParallelCluster.

Please let us know if you have any questions.
